### ISSUE TITLE
Issues building on i9 Intel Mac

### ISSUE THREAD

**Issue by lukes-anger** [v7b1/mi-UGens#21]
Hello, I've been trying to get these UGens built on OSX. 
It gets around 12% through the build, then fails:
`3 errors generated.
make[2]: *** [projects/MiBraids/CMakeFiles/MiBraids.dir/MiBraids.cpp.o] Error 1
make[1]: *** [projects/MiBraids/CMakeFiles/MiBraids.dir/all] Error 2
make: *** [all] Error 2` 
Any ideas?
Thanks!

**Comment by v7b1** [comment]
Hi, since it fails on MiBraids it could be libsamplerate related, but without more info about the actual errors this is just guess work. As a quick test, you could comment out 
`add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/projects/MiBraids)`
(and possibly also 
`add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/projects/MiBraids/libsamplerate ${CMAKE_CURRENT_SOURCE_DIR}/projects/MiBraids/libsamplerate/build)` )
from CMakeLists.txt in the root directory and see if that gets you past the errors.

**Comment by lukes-anger** [comment]
Thanks for the reply! I tried the above, however it fails in a similar fashion on the next step (clouds). 
I'll paste more of the stack trace below in case it makes any more sense.
Would really appreciate any suggestions as I'm keen to get these working!

```
-- Build files have been written to: /Users/luke/Desktop/mi-UGens/build
[  1%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/__/__/eurorack/stmlib/utils/random.cc.o
[  2%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/__/__/eurorack/stmlib/dsp/atan.cc.o
[  3%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/__/__/eurorack/stmlib/dsp/units.cc.o
[  4%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/__/__/eurorack/clouds/dsp/correlator.cc.o
[  5%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/__/__/eurorack/clouds/dsp/granular_processor.cc.o
[  6%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/__/__/eurorack/clouds/dsp/mu_law.cc.o
[  7%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/__/__/eurorack/clouds/dsp/pvoc/frame_transformation.cc.o
[  8%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/__/__/eurorack/clouds/dsp/pvoc/phase_vocoder.cc.o
[  9%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/__/__/eurorack/clouds/dsp/pvoc/stft.cc.o
[ 10%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/__/__/eurorack/clouds/resources.cc.o
[ 11%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/MiClouds.cpp.o
In file included from /Users/luke/Desktop/mi-UGens/projects/MiClouds/MiClouds.cpp:32:
In file included from /Users/luke/Desktop/supercollider/include/plugin_interface/SC_PlugIn.h:25:
/Users/luke/Desktop/supercollider/include/plugin_interface/SC_Unit.h:96:2: error: expected expression
[[nodiscard]] inline constexpr auto copyAndCastToTypeOfFirstArg(const ToType&, const Value& value) noexcept {
 ^
/Users/luke/Desktop/supercollider/include/plugin_interface/SC_Unit.h:96:15: error: expected unqualified-id
[[nodiscard]] inline constexpr auto copyAndCastToTypeOfFirstArg(const ToType&, const Value& value) noexcept {
              ^
In file included from /Users/luke/Desktop/mi-UGens/projects/MiClouds/MiClouds.cpp:32:
In file included from /Users/luke/Desktop/supercollider/include/plugin_interface/SC_PlugIn.h:27:
/Users/luke/Desktop/supercollider/include/plugin_interface/SC_InterfaceTable.h:74:80: error: unknown type name 'UnitCmdFunc'
    bool (*fDefineUnitCmd)(const char* inUnitClassName, const char* inCmdName, UnitCmdFunc inFunc);
                                                                               ^
3 errors generated.
make[2]: *** [projects/MiClouds/CMakeFiles/MiClouds.dir/MiClouds.cpp.o] Error 1
make[1]: *** [projects/MiClouds/CMakeFiles/MiClouds.dir/all] Error 2
make: *** [all] Error 2
[  1%] Building CXX object projects/MiClouds/CMakeFiles/MiClouds.dir/MiClouds.cpp.o
In file included from /Users/luke/Desktop/mi-UGens/projects/MiClouds/MiClouds.cpp:32:
In file included from /Users/luke/Desktop/supercollider/include/plugin_interface/SC_PlugIn.h:25:
/Users/luke/Desktop/supercollider/include/plugin_interface/SC_Unit.h:96:2: error: expected expression
[[nodiscard]] inline constexpr auto copyAndCastToTypeOfFirstArg(const ToType&, const Value& value) noexcept {
 ^
/Users/luke/Desktop/supercollider/include/plugin_interface/SC_Unit.h:96:15: error: expected unqualified-id
[[nodiscard]] inline constexpr auto copyAndCastToTypeOfFirstArg(const ToType&, const Value& value) noexcept {
              ^
In file included from /Users/luke/Desktop/mi-UGens/projects/MiClouds/MiClouds.cpp:32:
In file included from /Users/luke/Desktop/supercollider/include/plugin_interface/SC_PlugIn.h:27:
/Users/luke/Desktop/supercollider/include/plugin_interface/SC_InterfaceTable.h:74:80: error: unknown type name 'UnitCmdFunc'
    bool (*fDefineUnitCmd)(const char* inUnitClassName, const char* inCmdName, UnitCmdFunc inFunc);
                                                                               ^
3 errors generated.
make[2]: *** [projects/MiClouds/CMakeFiles/MiClouds.dir/MiClouds.cpp.o] Error 1
make[1]: *** [projects/MiClouds/CMakeFiles/MiClouds.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by v7b1** [comment]
Ok, seems there are some breaking changes in the latest sc-headers. Don't have time to invest right now. You could fetch some older sc sources (I've built the UGens against a 2020 sc-version) and try your luck. 
Did you actually try to run the UGen files from [releases](https://github.com/v7b1/mi-UGens/releases) - they should support both arcs (x86_64 and arm64)?

**Comment by lukes-anger** [comment]
Hey, great suggestion. I tried a couple of older versions and got it working with [version 3.12.1](https://github.com/supercollider/supercollider/releases/tag/Version-3.12.1) 

The UGens from releases trigger the annoying OSX 'unknown developer' warning when you load SC and don't appear to work, I had the same issue installing the ported-plugins recently. Anyway, all good! Look forward to messing about with these.
